In [3]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
ar=np.arange(1,10,2)
print(ar)

[1 3 5 7 9]


In [9]:
arr=np.zeros(4,int)
print(arr)

[0 0 0 0]


In [12]:
#indentiy matrix in 
ar=np.eye(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# diagonal matrix
arr=np.diag([1,3,4])
print(arr)

[[1 0 0]
 [0 3 0]
 [0 0 4]]


In [14]:
a=np.diag([1,1,1])
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
### Radom generation in Numpy
b=np.random.rand(4)
print(b)



[0.75512607 0.69540347 0.14218977 0.05998051]


In [21]:
b=np.random.randint(2,12,10)
print(b)
print(b.max())
print("the minimun value of this list::")
print(b.min())

[10  9  5  6  7  2  9  9 11 11]
11
the minimun value of this list::
2


In [22]:
print(np.diag([1,1,1]))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [29]:
import numpy as np
arr=np.random.randint(0,100,16)
print(arr)

[80 23 24 72 80 97  2 27 80 35 28 14 62 93 95 83]


In [28]:
print(arr[1:4])

[81 76 47]


In [31]:
arr2d=np.random.randint(0,100,(4,4))
print(arr2d)

[[72 14 90 91]
 [ 0 12 55 39]
 [60 54 78 52]
 [72  3 30 46]]


In [32]:
print(arr2d[1])

[ 0 12 55 39]


In [34]:
print(arr2d[3][0])

72


In [37]:
t=np.arange(0,12).reshape(4,3)
print(t)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
print(t[0:2,0:2])

[[0 1]
 [3 4]]


In [44]:
print(t[2:4,1:3])

[[ 7  8]
 [10 11]]


In [47]:
arr1=np.arange(1,13)
arr2=np.arange(5,17)
print(arr1)
print(arr2)
print(arr1+arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12 13 14 15 16]
[ 6  8 10 12 14 16 18 20 22 24 26 28]


In [48]:
#maniul matrix cration 
ar=np.array([
    [1,3,4],
    [5,6,7],
    [44,2,1]
])
print(ar)

[[ 1  3  4]
 [ 5  6  7]
 [44  2  1]]


In [51]:
print(ar.dtype)

int32


In [52]:
print(ar.ndim)

2


In [53]:
print(ar.size)

9
